files:
  - source: /common/src/main/resources/assets/hiddenworldborder/lang/%locale_with_underscore%.json
    translation: /common/src/main/resources/assets/hiddenworldborder/lang/%locale_with_underscore%.json
